name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        echo "${DOCKER_HUB_PASSWORD}" | docker login \
          -u "${DOCKER_HUB_USERNAME}" --password-stdin docker.io
        docker build . --file busy.dockerfile \
          --tag docker.io/${DOCKER_HUB_USERNAME}/${DOCKER_HUB_REPOSITORY}:$GITHUB_SHA
        docker push docker.io/${DOCKER_HUB_USERNAME}/${DOCKER_HUB_REPOSITORY}:$GITHUB_SHA
